### ISSUE TITLE
Bug Panel

### ISSUE THREAD

**Issue by Soowarez** [obgp/OpenBalkanGamePanel#1]
Hello,
 
I would like to contact you because currently I have a problem installing your beautiful panel « Open Balkan GamePanel (v3.0) »
 
When I execute your order:
 
wget https://raw.githubusercontent.com/obgp/Auto-Install/master/install.sh;chmod 777 install.sh;bash install.sh;
 
![Capture d’écran 2019-10-22 à 12 09 43](https://user-images.githubusercontent.com/29873403/67277058-40d65100-f4c6-11e9-9fe0-7314e4bf1a61.png)

The installation proceeds correctly without error, once finished impossible to access the panel (see photo)
 

Can you help me fix this problem?
 
What are the server level prerequisites for the panel to work?
 
Thank you

**Comment by Soowarez** [comment]
do you have a date to contact us when the panel is finished?

**Comment by R00tS3c** [comment]
i will try to finish this week

**Comment by R00tS3c** [comment]
Now working all features but is not done
