### ISSUE TITLE
Dosta stvari ne rade

### ISSUE THREAD

**Issue by rudarot** [obgp/OpenBalkanGamePanel#2]
Jel se jos radi na ovo ili?

**Comment by R00tS3c** [comment]
Jednom kad budem seo da zavrsim da

**Comment by Blagii** [comment]
da li ce u skorije vreme moci da se koristi

**Comment by R00tS3c** [comment]
pa moze i sad ali me mrzi da pisem kako da ga podesis

**Comment by Blagii** [comment]
aj molim te napisi
